server:
  port: '9090'
spring:
  profiles:
    active: h2
---
spring:
  config:
    activate:
      on-profile: h2,ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/shareit'
    password: shareit
    username: shareit
---
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  datasource:
    url: 'jdbc:postgresql://localhost:6541/shareit'
    password: shareit
    username: shareit